# Generated by Django 5.0.2 on 2024-04-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternatif',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Alternatif'},
        ),
        migrations.AlterModelOptions(
            name='divisi',
            options={'verbose_name_plural': 'Divisi'},
        ),
        migrations.AlterField(
            model_name='alternatif',
            name='divisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.divisi'),
        ),
    ]
