# Generated by Django 5.0.2 on 2024-04-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_alternatif_options_alter_divisi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kriteria', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_kriteria', models.CharField(max_length=100)),
                ('bobot', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
            ],
        ),
    ]
