# Generated by Django 5.0.2 on 2024-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_kriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sub_kriteria', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kriteria',
            options={'verbose_name_plural': 'Kriteria'},
        ),
    ]
