# Generated by Django 5.0.2 on 2024-11-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subcriteria_perbandingan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=20)),
                ('bobot', models.FloatField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Perhitungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.alternative')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.criterion')),
                ('sub_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_akhir', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.alternative')),
            ],
        ),
    ]
